defaults:
  - _self_
  - task: default_task
  - agent: hiql

name: robot_${task.name}
_target_: ogcrl.workspace.robotworkspace.RobotWorkspace

task_name: ${task.name}
exp_name: "default"

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True

logging:
  mode: online
  
hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}

run_group: Debug
env_name: robofactory
save_dir: /media/data01/wangyi/liangziyan/mangobench_manipulation/logs/IHIQL_LiftBarrier_test_train

train_steps: 1000000
log_interval: 5000
eval_interval: 100000
save_interval: 1000000

eval_tasks: null
eval_episodes: 20
eval_temperature: 0
eval_gaussian: null
video_episodes: 1
video_frame_skip: 3
eval_on_cpu: 1
save_goal: True
save_goal_path: /media/data01/wangyi/liangziyan/mangobench_manipulation/logs/debug_ogcrl/debug_goals.pkl
wandb_name: ""
observation: null  # "state" or "visual" or "both"

agent:
  _target_: "ogcrl.agents.hiql.HIQLAgent"
  config_path: "agents/hiql.py"
