name: task_config

dataset:
  _target_: ogcrl.dataset.robot_image_dataset.RobotImageDataset
  zarr_path: /media/disk/wangyi/RoboFactory/robofactory/data/zarr_data/LiftBarrier-rf_Agent0_150.zarr
  horizon: 1
  pad_before: 0
  pad_after: 0
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
